INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53570)
INFO:root:Connected ('127.0.0.1', 53571)
INFO:root:Connected ('127.0.0.1', 53572)
INFO:root:Request parsing by connection started
INFO:root:Threaded client serving started ('127.0.0.1', 53570) in thread 4539334080
INFO:root:Parsing request by file started
INFO:root:Threaded client serving started ('127.0.0.1', 53571) in thread 4539334080
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Threaded client serving started ('127.0.0.1', 53572) in thread 4539334080
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53570) method: GET
target: /27-me/09/page-load-errors.css
version: HTTP/1.1
headers: Host: localhost:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://localhost:8000/27-me/09/2000
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x107fc6350>
user: ('127.0.0.1', 53570)
url: ParseResult(scheme='', netloc='', path='/27-me/09/page-load-errors.css', params='', query='', fragment='')
path: /27-me/09/page-load-errors.css
query: {}
INFO:root:Request parsed from ('127.0.0.1', 53571) method: GET
target: /27-me/09/page-load-errors-extras.css
version: HTTP/1.1
headers: Host: localhost:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://localhost:8000/27-me/09/2000
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x107fc64d0>
user: ('127.0.0.1', 53571)
url: ParseResult(scheme='', netloc='', path='/27-me/09/page-load-errors-extras.css', params='', query='', fragment='')
path: /27-me/09/page-load-errors-extras.css
query: {}
INFO:root:Request parsed from ('127.0.0.1', 53572) method: GET
target: /27-me/09/2000
version: HTTP/1.1
headers: Host: localhost:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x107fc6530>
user: ('127.0.0.1', 53572)
url: ParseResult(scheme='', netloc='', path='/27-me/09/2000', params='', query='', fragment='')
path: /27-me/09/2000
query: {}
INFO:root:Path processing /27-me/09/page-load-errors.css
INFO:root:Path processing /27-me/09/page-load-errors-extras.css
INFO:root:Path processing /27-me/09/2000
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/27-me/09/page-load-errors.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.2000.png
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/27-me/09/page-load-errors.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /dates/2000/09/27/me.png
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.page-load-errors.css.png
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.page-load-errors-extras.css.png
ERROR:root:Client handling failed (123145456971776) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/2000] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/[day]-[n]/[month]/[year]': '/dates/[year]/[month]/[day]/[n].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /dates/page-load-errors.css/09/27/me.png
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /dates/page-load-errors-extras.css/09/27/me.png
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/27-me/09/page-load-errors.css
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/27-me/09/page-load-errors-extras.css
ERROR:root:Client handling failed (123145446461440) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/page-load-errors-extras.css] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/[day]-[n]/[month]/[year]': '/dates/[year]/[month]/[day]/[n].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
ERROR:root:Client handling failed (123145451716608) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/page-load-errors-extras.css] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/[day]-[n]/[month]/[year]': '/dates/[year]/[month]/[day]/[n].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
INFO:root:1089B sent to ('127.0.0.1', 53572)
INFO:root:Files sent to ('127.0.0.1', 53572)
INFO:root:1089B sent to ('127.0.0.1', 53570)
INFO:root:1089B sent to ('127.0.0.1', 53571)
INFO:root:Files sent to ('127.0.0.1', 53570)
INFO:root:Files sent to ('127.0.0.1', 53571)
INFO:root:server is DOWN with no exceptions
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53583)
INFO:root:Connected ('127.0.0.1', 53584)
INFO:root:Connected ('127.0.0.1', 53585)
INFO:root:Threaded client serving started ('127.0.0.1', 53583) in thread 4357344704
INFO:root:Request parsing by connection started
INFO:root:Threaded client serving started ('127.0.0.1', 53584) in thread 4357344704
INFO:root:Parsing request by file started
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsing by connection started
INFO:root:Threaded client serving started ('127.0.0.1', 53585) in thread 4357344704
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53584) method: GET
target: /27-me/09/page-load-errors.css
version: HTTP/1.1
headers: Host: localhost:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://localhost:8000/27-me/09/2000
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x1025203b0>
user: ('127.0.0.1', 53584)
url: ParseResult(scheme='', netloc='', path='/27-me/09/page-load-errors.css', params='', query='', fragment='')
path: /27-me/09/page-load-errors.css
query: {}
INFO:root:Request parsed from ('127.0.0.1', 53585) method: GET
target: /27-me/09/page-load-errors-extras.css
version: HTTP/1.1
headers: Host: localhost:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://localhost:8000/27-me/09/2000
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x1025205f0>
user: ('127.0.0.1', 53585)
url: ParseResult(scheme='', netloc='', path='/27-me/09/page-load-errors-extras.css', params='', query='', fragment='')
path: /27-me/09/page-load-errors-extras.css
query: {}
INFO:root:Request parsed from ('127.0.0.1', 53583) method: GET
target: /27-me/09/2000
version: HTTP/1.1
headers: Host: localhost:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x102520410>
user: ('127.0.0.1', 53583)
url: ParseResult(scheme='', netloc='', path='/27-me/09/2000', params='', query='', fragment='')
path: /27-me/09/2000
query: {}
INFO:root:Path processing /27-me/09/page-load-errors.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/27-me/09/page-load-errors.css
INFO:root:Path processing /27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/27-me/09/page-load-errors.css
INFO:root:Path processing /27-me/09/2000
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /dates/page-load-errors.css/09/27/me.png
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /dates/2000/09/27/me.png
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.page-load-errors.css.png
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.2000.png
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /dates/page-load-errors-extras.css/09/27/me.png
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/27-me/09/page-load-errors.css
ERROR:root:Client handling failed (123145330225152) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/page-load-errors.css] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[day]-[n]/[month]/[year]': '/dates/[year]/[month]/[day]/[n].png', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.page-load-errors-extras.css.png
ERROR:root:Client handling failed (123145335480320) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/page-load-errors.css] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[day]-[n]/[month]/[year]': '/dates/[year]/[month]/[day]/[n].png', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/27-me/09/page-load-errors-extras.css
INFO:root:1089B sent to ('127.0.0.1', 53583)
ERROR:root:Client handling failed (123145340735488) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/page-load-errors-extras.css] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[day]-[n]/[month]/[year]': '/dates/[year]/[month]/[day]/[n].png', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
INFO:root:Files sent to ('127.0.0.1', 53583)
INFO:root:1089B sent to ('127.0.0.1', 53584)
INFO:root:Files sent to ('127.0.0.1', 53584)
INFO:root:1089B sent to ('127.0.0.1', 53585)
INFO:root:Files sent to ('127.0.0.1', 53585)
INFO:root:server is DOWN with no exceptions
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53595)
INFO:root:Connected ('127.0.0.1', 53596)
INFO:root:Connected ('127.0.0.1', 53597)
INFO:root:Threaded client serving started ('127.0.0.1', 53595) in thread 4597415360
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Threaded client serving started ('127.0.0.1', 53596) in thread 4597415360
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Threaded client serving started ('127.0.0.1', 53597) in thread 4597415360
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53596) method: GET
target: /27-me/09/page-load-errors.css
version: HTTP/1.1
headers: Host: localhost:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://localhost:8000/27-me/09/2000
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x10cb6a4d0>
user: ('127.0.0.1', 53596)
url: ParseResult(scheme='', netloc='', path='/27-me/09/page-load-errors.css', params='', query='', fragment='')
path: /27-me/09/page-load-errors.css
query: {}
INFO:root:Request parsed from ('127.0.0.1', 53595) method: GET
target: /27-me/09/2000
version: HTTP/1.1
headers: Host: localhost:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x10cb6a350>
user: ('127.0.0.1', 53595)
url: ParseResult(scheme='', netloc='', path='/27-me/09/2000', params='', query='', fragment='')
path: /27-me/09/2000
query: {}
INFO:root:Request parsed from ('127.0.0.1', 53597) method: GET
target: /27-me/09/page-load-errors-extras.css
version: HTTP/1.1
headers: Host: localhost:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://localhost:8000/27-me/09/2000
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x10cb6a470>
user: ('127.0.0.1', 53597)
url: ParseResult(scheme='', netloc='', path='/27-me/09/page-load-errors-extras.css', params='', query='', fragment='')
path: /27-me/09/page-load-errors-extras.css
query: {}
INFO:root:Path processing /27-me/09/page-load-errors.css
INFO:root:Path processing /27-me/09/2000
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/27-me/09/page-load-errors.css
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/2000/09/27/me.png
INFO:root:Path processing /27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/27-me/09/page-load-errors.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/page-load-errors.css/09/27/me.png
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.page-load-errors.css.png
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/page-load-errors-extras.css/09/27/me.png
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/27-me/09/page-load-errors.css
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.page-load-errors-extras.css.png
ERROR:root:Client handling failed (123145532710912) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/page-load-errors.css] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[day]-[n]/[month]/[year]': 'tmp/dates/[year]/[month]/[day]/[n].png', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'inode/x-empty'), ('Content-Disposition', 'inline; filename=me.png'), ('Content-Length', 0)]
body: b''
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/27-me/09/page-load-errors-extras.css
ERROR:root:Client handling failed (123145537966080) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/page-load-errors-extras.css] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[day]-[n]/[month]/[year]': 'tmp/dates/[year]/[month]/[day]/[n].png', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
INFO:root:1089B sent to ('127.0.0.1', 53596)
INFO:root:113B sent to ('127.0.0.1', 53595)
INFO:root:Files sent to ('127.0.0.1', 53596)
INFO:root:Files sent to ('127.0.0.1', 53595)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'inode/x-empty'), ('Content-Disposition', 'inline; filename=me.png'), ('Content-Length', 0)]
body: b''
INFO:root:1089B sent to ('127.0.0.1', 53597)
INFO:root:Files sent to ('127.0.0.1', 53597)
INFO:root:server is DOWN with no exceptions
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53607)
INFO:root:Connected ('127.0.0.1', 53608)
INFO:root:Connected ('127.0.0.1', 53609)
INFO:root:Threaded client serving started ('127.0.0.1', 53607) in thread 4449541568
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Threaded client serving started ('127.0.0.1', 53608) in thread 4449541568
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Threaded client serving started ('127.0.0.1', 53609) in thread 4449541568
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53607) method: GET
target: /27-me/09/2000
version: HTTP/1.1
headers: Host: localhost:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x109af1350>
user: ('127.0.0.1', 53607)
url: ParseResult(scheme='', netloc='', path='/27-me/09/2000', params='', query='', fragment='')
path: /27-me/09/2000
query: {}
INFO:root:Request parsed from ('127.0.0.1', 53608) method: GET
target: /27-me/09/page-load-errors.css
version: HTTP/1.1
headers: Host: localhost:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://localhost:8000/27-me/09/2000
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x109af1530>
user: ('127.0.0.1', 53608)
url: ParseResult(scheme='', netloc='', path='/27-me/09/page-load-errors.css', params='', query='', fragment='')
path: /27-me/09/page-load-errors.css
query: {}
INFO:root:Request parsed from ('127.0.0.1', 53609) method: GET
target: /27-me/09/page-load-errors-extras.css
version: HTTP/1.1
headers: Host: localhost:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://localhost:8000/27-me/09/2000
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x109af14d0>
user: ('127.0.0.1', 53609)
url: ParseResult(scheme='', netloc='', path='/27-me/09/page-load-errors-extras.css', params='', query='', fragment='')
path: /27-me/09/page-load-errors-extras.css
query: {}
INFO:root:Path processing /27-me/09/2000
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/2000/09/27/me.png
INFO:root:Path processing /27-me/09/page-load-errors.css
INFO:root:Path processing /27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/27-me/09/page-load-errors.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/27-me/09/page-load-errors.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/27-me/09/page-load-errors-extras.css
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/page-load-errors.css/09/27/me.png
ERROR:root:Path matched by rule re.compile('/(?P<day>.*)-(?P<n>.*)/(?P<month>.*)/(?P<year>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/page-load-errors-extras.css/09/27/me.png
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'inode/x-empty'), ('Content-Disposition', 'inline; filename=me.png'), ('Content-Length', 0)]
body: b''
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.page-load-errors.css.png
ERROR:root:Path matched by rule re.compile('/(?P<DD>.*)/(?P<MM>.*)/(?P<YY>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/dates/27-me.09.page-load-errors-extras.css.png
INFO:root:113B sent to ('127.0.0.1', 53607)
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/27-me/09/page-load-errors.css
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/27-me/09/page-load-errors-extras.css
INFO:root:Files sent to ('127.0.0.1', 53607)
ERROR:root:Client handling failed (123145472385024) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/page-load-errors-extras.css] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[day]-[n]/[month]/[year]': 'tmp/dates/[year]/[month]/[day]/[n].png', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
ERROR:root:Client handling failed (123145477640192) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 226, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /27-me/09/page-load-errors-extras.css] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[day]-[n]/[month]/[year]': 'tmp/dates/[year]/[month]/[day]/[n].png', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 115, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 228, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'inode/x-empty'), ('Content-Disposition', 'inline; filename=me.png'), ('Content-Length', 0)]
body: b''
INFO:root:1089B sent to ('127.0.0.1', 53608)
INFO:root:Files sent to ('127.0.0.1', 53608)
INFO:root:1089B sent to ('127.0.0.1', 53609)
INFO:root:Files sent to ('127.0.0.1', 53609)
INFO:root:server is DOWN with no exceptions
